// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8tfkgT9MVb5VP6-hY1S_kAVK2ikEOGL8',
    appId: '1:784228817120:web:c4e5ac79e8d9b9023a1885',
    messagingSenderId: '784228817120',
    projectId: 'medigine-d2faf',
    authDomain: 'medigine-d2faf.firebaseapp.com',
    storageBucket: 'medigine-d2faf.appspot.com',
    measurementId: 'G-VK3X16KFZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHu0r6gUh0A_jpG05Jt_sXVfo0ChN4IF8',
    appId: '1:784228817120:android:ebf5ecb702386c333a1885',
    messagingSenderId: '784228817120',
    projectId: 'medigine-d2faf',
    storageBucket: 'medigine-d2faf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOj3rMJbMz1zhQX7vAJ70rw71ZE-4WIdg',
    appId: '1:784228817120:ios:2809850eb191b8e53a1885',
    messagingSenderId: '784228817120',
    projectId: 'medigine-d2faf',
    storageBucket: 'medigine-d2faf.appspot.com',
    iosBundleId: 'com.example.medigine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOj3rMJbMz1zhQX7vAJ70rw71ZE-4WIdg',
    appId: '1:784228817120:ios:2809850eb191b8e53a1885',
    messagingSenderId: '784228817120',
    projectId: 'medigine-d2faf',
    storageBucket: 'medigine-d2faf.appspot.com',
    iosBundleId: 'com.example.medigine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8tfkgT9MVb5VP6-hY1S_kAVK2ikEOGL8',
    appId: '1:784228817120:web:cad2d63901154bf13a1885',
    messagingSenderId: '784228817120',
    projectId: 'medigine-d2faf',
    authDomain: 'medigine-d2faf.firebaseapp.com',
    storageBucket: 'medigine-d2faf.appspot.com',
    measurementId: 'G-KT5X2FNMJ1',
  );
}
